using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace JazzRelay.Enums
{
    public enum PacketType : byte
    {
        Failure = 0,
        Hello = 74,
        CreateSuccess = 101,
        Goto = 18,
        MapInfo = 92,
        NewTick = 10,
        Ping = 8,
        Pong = 31,
        GotoAck = 65,
        Reconnect = 45,
        Update = 42,
        UpdateAck = 81,
        Load = 61,
        Create = 57,
        Move = 62,
        UsePortal = 47,
        ResetDailyQuests = 52,
        GoToQuestRoom = 48,
        Teleport = 1,
        RequestTrade = 5,
        VaultUpdate = 117,
        InvSwap = 55,
        //InvDrop = 55,
        Escape = 105,
        ChangePetSkin = 33,
        GuildRemove = 15,
        GuildResult = 26,
        EditAccountList = 27,
        ClientStat = 69,
        UseItem = 13,
        Text = 44,
        InvResult = 95,
        ChangeGuildRank = 37,
        AcceptTrade = 36,
        TradeAccepted = 14,
        TradeDone = 34,
        TradeRequested = 88,
        TradeStart = 86,
        ChangeTrade = 56,
        PlayerText = 9,
        ChooseName = 97,
        JoinGuild = 7,
        CheckCredits = 102,
        ActivePetUpdateRequest = 24,
        ChatHello = 106,
        AoeAck = 89,
        SetCondition = 60,
        PlayerShoot = 30,
        EnterArena = 17,
        AcceptArenaDeath = 80,
        GroundDamage = 103,
        GuildInvite = 104,
        ShowEffect = 11,
        ShootAck = 100,
        PlayerHit = 90,
        QuestObjectId = 82,
        Death = 46,
        AllyShoot = 49,
        QueuePosition = 112,
        EnemyHit = 25,
        EnemyShoot = 35,
        Buy = 85,
        FeedPet = 16,
        BuyResult = 22,
        ActivePet = 76,
        KeyInfoRequest = 94,
        CreateGuild = 59,
        QuestRedeem = 58,
        ClaimDailyReward = 3,
        CancelTrade = 91,
        OtherHit = 20,
        SquareHit = 40,
        QuestFetchAsk = 98,
        Forge = 118,
        InvitedToGuild = 77,
        QuestRedeemResponse = 96,
        Damage = 75,
        TradeChanged = 28,
        Unknown7A = 0x7a,
        ServerPlayerShoot = 12,
        ShootAckCounter = 121,
        Notification = 67,
        ProjectileAck = 100
    }
}
